name: CI
on:
  pull_request:

jobs:
  cargo-test:
    strategy:
      # Prevent GitHub from cancelling all in-progress jobs when a matrix job fails.
      fail-fast: false
      matrix:
        os: [windows-latest]
        # TODO: add windows-latest (see #566)
    runs-on: ${{ matrix.os }}
    env:
      openssl-dir: "openssl"

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable
          profile: minimal
      # Smart caching for Rust projects.
      # Includes workaround for macos cache corruption.
      # - https://github.com/rust-lang/cargo/issues/8603
      # - https://github.com/actions/cache/issues/403
      - uses: Swatinem/rust-cache@v1

      - name: install openssl
        if: matrix.os == 'windows-latest'
        run: |
          choco install --verbose openssl
          openssl version
          which openssl
          echo "OPENSSL_LIB_DIR=$( which openssl )" >> $env:GITHUB_ENV
          echo "OPENSSL_DIR=$( which openssl )" >> $env:GITHUB_ENV

      # Real CI work starts here
      - name: Build workspace
        run: |
          cargo build